# Start vault server locally for the purposes of integration tests.
version: "3.0"
services:
  vault:
    image: vault:1.3.0
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
    ports:
      - 8200:8200
    privileged: true
  vault-enterprise:
    image: hashicorp/vault-enterprise:1.3.0_ent
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
    ports:
      - 8201:8200
    privileged: true
